name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 16
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: npm lint
      run: npm run lint -- --fix
    - name: npm build
      run: npm run build
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: dist/
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
      with:
        token: ${{ github.token }}
